org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_version=0.4.1

mod_id=minigames
mod_name=Custom Mini Games
mod_license=MIT
mod_authors=1whohears
mod_description=Adds a bunch of minigame modes that can be started with the /minigame command.

maven_group=com.onewhohears.minigames
archives_name=minigames
enabled_platforms = fabric,forge

homepage=https://github.com/1whohears
sources=https://github.com/1whohears/CustomMiniGames
issue_tracker=https://github.com/1whohears/CustomMiniGames/issues

minecraft_version=1.20.1
minecraft_version_range=[1.20.1]

architectury_version = 9.2.14

fabric_loader_version = 0.17.2
fabric_api_version = 0.92.6+1.20.1

forge_version = 1.20.1-47.4.0
forge_version_range=[47,)
forge_loader_version_range=[47,)

onewholibs_version=2.0.18

xaeros_minimap_fair_play_version = 24.2
xaeros_minimap_fair_play_id_forge = 5548212
xaeros_minimap_fair_play_id_fabric = 5548207

tacz_version = 1.1.4
tacz_id_forge = 6654541