modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"
issueTrackerURL="https://github.com/1whohears/CustomMiniGames/issues"
showAsResourcePack=false

[[mods]]
	modId="minigames"
	version="${file.jarVersion}"
	displayName="Custom Mini Games"
	logoFile="minigames.png"
    displayURL="https://modrinth.com/mod/custom-mini-games"
    updateJSONURL="https://raw.githubusercontent.com/1whohears/ModVersions/main/CustomMiniGames/update.json"
	displayTest = "MATCH_VERSION"
	authors="1whohears"
	credits="My Lizard"
	description="Adds a bunch of mini game modes that can be started with the /minigame command."

[[dependencies.minigames]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minigames]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.minigames]]
    modId = "onewholibs"
    mandatory = true
    versionRange = "[1.6.3,)"
    ordering = "NONE"
    side = "BOTH"
